deploymentName : cart-deployment
deploymentLabel : cart-service

replicaCount: 1

image:
  repository: pranayraut11/cart-app
  tag: latest

containerPort: 8080

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30002

config:
  enabled: true
profile:
  enabled: true
mongo:
  enabled: false
redis: 
  enabled: true

keycloak:
  resource: cart-service
  credentials:
    secret: 9QdxFnJZWnEzgFaptuR8ytT0wY0I2FMN

app:
  envVars:
    - name: SPRING_REDIS_HOST
      value: {{ .Values.global.redisUrl }}
    - name: SPRING_REDIS_PASSWORD
      value: redis123
    - name: KEYCLOAK_RESOURCE
      value: cart-service
    - name: KEYCLOAK_CREDENTIALS_SECRET
      value: 9QdxFnJZWnEzgFaptuR8ytT0wY0I2FMN
