deploymentName : cart
deploymentLabel : cart-deployment

replicaCount: 1

image:
  repository: pranayraut11/cart-app
  tag: latest

containerPort: 7002

service:
  type: NodePort
  port: 8081
  targetPort: 7002
  nodePort: 30002

config:
  enabled: true
profile:
  enabled: true
mongo:
    enabled: false

