deploymentName : cart
deploymentLabel : cart-deployment

replicaCount: 1

image:
  repository: pranayraut11/cart-app
  tag: latest

containerPort: 8080

service:
  type: NodePort
  port: 7002
  targetPort: 8080
  nodePort: 30002

config:
  enabled: true
profile:
  enabled: true
mongo:
  enabled: false
redis: 
  enabled: true
