apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    name: mongodb-deployment
    app: ecom

spec:
  template:
    metadata:
      name: mongodb-pod
      labels:
        name: mongodb-pod
        app: ecom
    spec: 
      containers:
        - name: mongodb-pod
          image: mongo
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: mongodb-secret
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: mongodb-secret
          - name: MONGO_INITDB_DATABASE
            value: admin
  replicas: 3      
  selector:
    matchLabels:
      name: mongodb-pod
      app: ecom    

