version: "3.4"
services:
    catalog1:
     build: ./Services/cart
     ports:
         - "8081:8080"

    order1:
      build: ./Services/order
      ports:
          - "8082:8080"

    cart1:
      build: ./Services/catalog
      ports:
          - "8083:8080"

    mongodb:
      image: mongo