{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.deploymentLabel }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentLabel }}
    spec:
      containers:
        - name: {{ .Values.deploymentLabel }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort}}
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 250m
              memory: 250Mi
          env:
            - name: SECURITY_ENABLED
              value: {{ .Values.global.securityEnabled | quote }}
          {{- range .Values.service.envVars }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end }}
        {{- if eq .Values.startupProbe.enabled true }}
          startupProbe:
            httpGet:
              path: /app/started
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 50
        {{ end }}
          volumeMounts:
            - mountPath: /logs/
              name: data    
              
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: common-persistentvolumeclaim        
{{- end -}}
