apiVersion: v1
kind: ConfigMap
metadata:
  name: elk-filebeat-cfgmap
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /logs/*.log

    output.elasticsearch:
      hosts: 'elasticsearch:9200'

