apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: dev-env-ui
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecom-ui-deployment
                port:
                  number: 80
