services:
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        container_name: keycloak
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
            - "6080:8080"
        command:
            -   "start-dev"
