apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    name: cart
    app: ecom

spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30006
  selector:
    name: cart-pod
    app: ecom    
