apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    name: catalog
    app: ecom

spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: catalog-pod
    app: ecom    
