apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb-service
    app: ecom

spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongodb-pod
    app: ecom
  