apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-dev-persistentvolumeclaim

spec:
 storageClassName: manual
 accessModes: 
   - ReadWriteOnce

 resources: 
   requests:
     storage: 1Gi

 selector:
   matchLabels:
     name: common-dev-persistentvolume