apiVersion: v1
kind: PersistentVolume
metadata: 
  name: common-dev-persistentvolume
  labels:
    name: common-dev-persistentvolume

spec:
 accessModes:
   - ReadWriteOnce
 capacity: 
    storage: 1Gi
 hostPath:
  path: /data/
 storageClassName: manual
      