apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-infra
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec: 
  rules:
  - host: mongodb
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-env-mongodb 
            port: 
              number: 27017
  - host: redis
    http:
      paths:            
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-env-redis-master 
            port: 
              number: 6379  
  - host: postgresql
    http:
      paths:             
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-env-postgresql 
            port: 
              number: 5432  