server:
  port: 8082
keycloak:
  server-url: http://localhost:8080
  master-realm: master
  realm: ecom
  client-id: your-client-id
  client-secret: your-client-secret
  admin:
    username: admin
    password: admin
    client-id: admin-cli

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud.discovery:
    enabled: false