server:
  port: 8080

spring:
  application:
    name: cart-service
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:6080/realms/master
          jwk-set-uri: http://localhost:6080/realms/master/protocol/openid-connect/certs
    ########################### Redis DB details ##################
  redis:
    host: localhost
    port: 6379
    password:
    database: 0

####### Enable/Disable API security
security:
  enabled: true
########################### security details ##################
#auth.client-id = cart-service
#auth.client-secret = 9V0zChkiOPngT4hphaWZ8QRXlLE6m3d8
#auth.client-uri = http://localhost:8080/realms/ecom

#spring.security.oauth2.client.provider.ecom.issuer-uri=${auth.client-uri}
#spring.security.oauth2.client.registration.ecom.client-id=${auth.client-id}
#spring.security.oauth2.client.registration.ecom.client-secret=${auth.client-secret}
#spring.security.oauth2.client.registration.ecom.scope=openid
#spring.security.oauth2.client.registration.ecom.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.ecom.redirect-uri=http://localhost:9090/login/oauth2/code/employee-management-api


################# Spring ####################
#spring.main.allow-bean-definition-overriding=true
