apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mongo-persistentvolume
  labels:
    name: mongo-persistentvolume

spec:
 accessModes:
   - ReadWriteOnce
 capacity: 
    storage: 1Gi
 hostPath:
  path: /run/desktop/mnt/host/c/storage/MongoData
 storageClassName: manual
      