deploymentName : catalog
deploymentLabel : catalog-deployment

replicaCount: 1

image:
  repository: pranayraut11/catalog-app
  tag: latest

containerPort: 8080

service:
  type: NodePort
  port: 7001
  targetPort: 8080
  nodePort: 30001

config:
  enabled: true
profile:
  enabled: true
mongo:
    enabled: true
redis: 
  enabled: false    

