deploymentName : catalog
deploymentLabel : catalog-deployment

replicaCount: 1

image:
  repository: pranayraut11/catalog-app
  tag: latest

containerPort: 7001

service:
  type: NodePort
  port: 8080
  targetPort: 7001
  nodePort: 30001

config:
  enabled: true
profile:
  enabled: true
mongo:
    enabled: true

