deploymentName : product-deployment
deploymentLabel : product-service

replicaCount: 1

image:
  repository: pranayraut11/product-app
  tag: latest

containerPort: 8080

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30001

config:
  enabled: true
profile:
  enabled: true
mongo:
    enabled: true
redis: 
  enabled: false

app:
  envVars:
    - name: KEYCLOAK_RESOURCE
      value: product-service
    - name: KEYCLOAK_CREDENTIALS_SECRET
      value: QXwxSfa1SYZ4pJUngrGzK66UBhDaYVNp   
    - name: APP_SERVICE_FILEMANAGER_HOST
      value: filemanager-service
    - name: SERVER_PORT
      value: '8080'  

