deploymentName : product-deployment
deploymentLabel : product

replicaCount: 1

image:
  repository: pranayraut11/product-app
  tag: latest

containerPort: 8080

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30001

config:
  enabled: true
profile:
  enabled: true
mongo:
    enabled: true
redis: 
  enabled: false

keycloak:
  resource: product-service
  credentials:
    secret: QXwxSfa1SYZ4pJUngrGzK66UBhDaYVNp

app:
  service:
    filemanager:
      host: filemanager  

