spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://mongodb:27017/?compressors=zlib&readPreference=primary&gssapiServiceName=mongodb&appname=MongoDB%20Compass&ssl=false
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
