server:
  port: 6061
spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecom
          jwk-set-uri: http://localhost:8080/realms/ecom/protocol/openid-connect/certs
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true
#      httpclient:
#        connect-timeout: 5000
#        response-timeout: 5s


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  fetch-registry: true
#  register-with-eureka: true
#  instance:
#    preferIpAddress: true