apiVersion: v2
name: ecom
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: mongodb
    version: 13.3.0
    repository: "https://charts.bitnami.com/bitnami"
  
  - name: redis
    version: 17.3.8
    repository: "https://charts.bitnami.com/bitnami"

  - name: postgresql
    version: 12.1.3
    repository: "https://charts.bitnami.com/bitnami"  
  
  - name: keycloak
    version: 12.2.0
    repository: "https://charts.bitnami.com/bitnami"

  - name: ecom-ui
    version: 0.1.0
    condition: ecom-ui.enabled
    repository: file://charts/ecom-ui

  - name: product-service
    version: 0.1.0
    condition: product-service.enabled
    repository: file://charts/product-service

  - name: cart-service
    version: 0.1.0
    condition: cart-service.enabled
    repository: file://charts/cart-service

  - name: user-service
    version: 0.1.0
    condition: user-service.enabled
    repository: file://charts/user-service

  - name: filemanager-service
    version: 0.1.0
    condition: filemanager-service.enabled
    repository: file://charts/filemanager-service

  - name: order-service
    version: 0.1.0
    condition: order-service.enabled
    repository: file://charts/order-service  
  
