global:
  configMapName: dev-configmap
  activeProfile: dev
  mongoUrl: mongodb://demo1:demo1@dev-env-mongodb:27017/product
  redisUrl: dev-env-redis-master
  securityEnabled: "true"


env:
  url: dev-env
  
 


mongodb:
  auth:
    enabled: true
    databases:
      - product
    usernames:
      - demo1
    passwords:
      - demo1
  persistence:
    enabled: true
    existingClaim: common-persistentvolumeclaim
  volumePermissions:
    enabled: true

redis:
  auth:
    enabled: true
    password: redis123
  replica:
    replicaCount: 1
    
postgresql:
  auth:
    enablePostgresUser: true
    postgresPassword: admin
    database: userauth
  persistence:
    enabled: true
    existingClaim: common-persistentvolumeclaim

keycloak:
  auth:
    adminUser: admin
    adminPassword: admin
  postgresql:
    enabled: false
  externalDatabase:
    host: dev-env-postgresql
    port: 5432
    user: postgres
    database: userauth
    password: admin
  ingress:
    enabled: true
    hostname: keycloak.local

minio:
  auth:
    rootUser: admin123
    rootPassword: admin123
  ingress:
    enabled: true
    hostname: minio.local
  persistence:
    enabled: true
    existingClaim: common-persistentvolumeclaim

ecom-ui:
  enabled: true

user-service:
  enabled: true
  service:
    envVars:
      - name: AUTH_SERVER_URL
        value: http://dev-env-keycloak
      - name: KEYCLOAK_RESOURCE
        value: user-service
      - name: KEYCLOAK_CREDENTIALS_SECRET
        value: s7Isa5HJrCyOhOQcbronywW5LAMjuPNR
      - name: USER_AUTH_REALMS_SUBREALMS
        value: ecom
      - name: USER_AUTH_SERVER_HOST
        value: "dev-env-keycloak"
      - name: USER_AUTH_REALMS_MASTER_ADMIN_CLIENTSECRET
        value: xaduD2SkxE0rlIKZiw7ksJX6iu1mpQP7
      - name: SPRING_DATA_MONGODB_URI
        value: "mongodb://demo1:demo1@dev-env-mongodb:27017/product"


product-service:
  enabled: true
  service:
    envVars:
      - name: AUTH_SERVER_URL
        value: http://dev-env-keycloak
      - name: KEYCLOAK_RESOURCE
        value: product-service
      - name: KEYCLOAK_CREDENTIALS_SECRET
        value: w09k8DLjY9h3AA1oIdAqxdNT9z7fS2PB
      - name: APP_SERVICE_FILEMANAGER_HOST
        value: filemanager-service
      - name: SPRING_DATA_MONGODB_URI
        value: "mongodb://demo1:demo1@dev-env-mongodb:27017/product"

cart-service:
  enabled: false
  service:
    envVars:
      - name: AUTH_SERVER_URL
        value: http://dev-env-keycloak
      - name: KEYCLOAK_RESOURCE
        value: cart-service
      - name: KEYCLOAK_CREDENTIALS_SECRET
        value: 9QdxFnJZWnEzgFaptuR8ytT0wY0I2FMN
      - name: SPRING_REDIS_HOST
        value: "dev-env-redis-master"
      - name: SPRING_REDIS_PASSWORD
        value: "redis123"


filemanager-service:
  enabled: true
  service:
    envVars:
      - name: AUTH_SERVER_URL
        value: http://dev-env-keycloak
      - name: KEYCLOAK_RESOURCE
        value: filemanager-service
      - name: KEYCLOAK_CREDENTIALS_SECRET
        value: 6BT3R8jXvDpAdyu96WDSEqrRNzP1i9dV
      - name: SPRING_DATA_MONGODB_URI
        value: "mongodb://demo1:demo1@dev-env-mongodb:27017/product"
      - name: MINIO_URL
        value:  dev-env-minio
      - name: MINIO_ACCESS_NAME
        value:  miniouser
      - name: MINIO_ACCESS_SECRET
        value:  miniopassword


inventory-service:
  enabled: true
  service:
    envVars:
      - name: AUTH_SERVER_URL
        value: http://dev-env-keycloak
      - name: KEYCLOAK_RESOURCE
        value: inventory-service
      - name: KEYCLOAK_CREDENTIALS_SECRET
        value: 9V0zChkiOPngT4hphaWZ8QRXlLE6m3d8
      - name: SPRING_DATA_MONGODB_URI
        value: "mongodb://demo1:demo1@dev-env-mongodb:27017/inventory"


orchestrator-service:
  enabled: true
  service:
    envVars:
      - name: AUTH_SERVER_URL
        value: http://dev-env-keycloak
      - name: KEYCLOAK_RESOURCE
        value: orchestrator-service
      - name: KEYCLOAK_CREDENTIALS_SECRET
        value: 9V0zChkiOPngT4hphaWZ8QRXlLE6m3d8
      - name: SPRING_DATA_MONGODB_URI
        value: "mongodb://demo1:demo1@dev-env-mongodb:27017/orchestrator"

