global:
  configMapName: dev-configmap
  activeProfile: dev
  mongoUrl: mongodb://demo1:demo1@dev-env-mongodb:27017/product
  redisUrl: dev-env-redis-master

mongodb:
  auth:
    enabled: true
    databases:
      - product
    usernames:
      - demo1
    passwords:
      - demo1
  persistence:
    enabled: true
    existingClaim: common-persistentvolumeclaim
  volumePermissions:
    enabled: true

redis: 
  auth:
    enabled: true     
    password: redis123

postgresql:
  auth:
    enablePostgresUser: true
    postgresPassword: admin
    database: userauth
  persistence:
    enabled: true
    existingClaim: common-persistentvolumeclaim
    
keycloak:
  auth:
    adminUser: admin
    adminPassword: admin
  postgresql:
    enabled: false
  externalDatabase:
    host: dev-env-postgresql
    port: 5432
    user: postgres
    database: userauth
    password: admin
  ingress: 
    enabled: true
    hostname: keycloak.dev

env: 
  url: dev-env    
