global:
  configMapName: dev-configmap
  activeProfile: dev
  mongoUrl: mongodb://demo:demo@dev-env-mongodb:27017/?authSource=admin
  redisUrl: dev-env-redis-master

mongodb:
  auth:
    enabled: true
    databases:
      - catalog
    usernames:
      - demo
    passwords:
      - demo

redis: 
  auth:
    enabled: true     
    password: redis123
