global:
  configMapName: dev-configmap
  activeProfile: default
  mongoUrl: mongodb://demo1:demo1@dev-env-mongodb:27017/product
  redisUrl: dev-env-redis-master

mongodb:
  auth:
    enabled: true
    databases:
      - product
    usernames:
      - demo1
    passwords:
      - demo1

redis: 
  auth:
    enabled: true     
    password: redis123
