{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.deploymentLabel }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentLabel }}
    spec:
      containers:
        - name: {{ .Values.deploymentLabel }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort}}
              protocol: TCP
          env: 
          {{- range .Values.app.envVars }}
            - name: {{ .name }}
              valueFrom: 
                configMapKeyRef:
                  name: {{ .Values.global.configMapName }}
                  key: {{ .name }}
          {{- end }}
          {{- if .Values.mongo.enabled }}
            - name: SPRING_DATA_MONGODB_URI
              valueFrom: 
                configMapKeyRef:
                  name: {{ .Values.global.configMapName }}
                  key: SPRING_DATA_MONGODB_URI
          {{- end -}}
          {{- if .Values.redis.enabled }}
            - name: SPRING_REDIS_HOST
              valueFrom: 
                configMapKeyRef:
                  name: {{ .Values.global.configMapName }}
                  key: SPRING_REDIS_HOST
            - name: SPRING_REDIS_PASSWORD
              valueFrom: 
                configMapKeyRef:
                  name: {{ .Values.global.configMapName }}
                  key: SPRING_REDIS_PASSWORD
          {{- end -}}
{{- end -}}          