apiVersion: v1
kind: ResourceQuota
metadata:
  name: resourcequota-dev
  namespace: dev

spec:
  hard:
    pods: "10"
    requests.cpu: "3"
    requests.memory: 3Gi
    limits.cpu: "5"
    limits.memory: 5Gi