deploymentName : inventory-deployment
deploymentLabel : inventory-service

replicaCount: 1

image:
  repository: pranayraut11/inventory-app
  tag: latest

containerPort: 8080

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30002
